### ISSUE TITLE
Extract(day from created_at) Query Grabbing Records From Different Months

### ISSUE THREAD

**Issue by TannerDale** [bullet-capstone/glow-up-be#54]
- When querying daily moods and habit entries, `extract(day from created_at)` will grab any records that fall on that day into the month, regardless of the month. 
- `2021-12-10`,  `2021-11-10`, and `2021-10-10` will all get selected when calling `extract(day from created_at)`  on Dec 10th

**Comment by WMudgeEllis** [comment]
For daily mood we are using find_by so, if there is a mood for today, it will be grabbed. The bug happens if there is no daily mood, then it will grab the previous month's mood.
